// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
  repositories {
    google()
    mavenCentral()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:8.7.2'
    classpath 'com.google.gms:google-services:4.4.2'
    // Usando a versão direta para evitar erros de variavel não carregada
    classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.20'

    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
  }
}

apply from: "variables.gradle"

allprojects {
  repositories {
    google()
    mavenCentral()
  }
}

// Isso vai iterar por todos os módulos (app, capacitor-google-maps, etc)
subprojects {
  afterEvaluate { project ->
    // Se o módulo for um projeto Android (App ou Biblioteca)...
    if (project.extensions.findByName("android") != null) {
      project.android {
        // ...Força o Java para 17
        compileOptions {
          sourceCompatibility = JavaVersion.VERSION_17
          targetCompatibility = JavaVersion.VERSION_17
        }
      }
    }
  }

  // Força o Kotlin para 17 em todos os módulos também
  tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
      jvmTarget = "17"
    }
  }
}

task clean(type: Delete) {
  delete rootProject.buildDir
}
